[package]
name = "zksync_shared"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vise.workspace = true
zksync_types.workspace = true
zksync_dal.workspace = true
anyhow.workspace = true
itertools.workspace = true
multivm.workspace = true
zksync_config.workspace = true
zksync_contracts.workspace = true
zksync_eth_client.workspace = true
zksync_merkle_tree.workspace = true
zksync_system_constants.workspace = true
zksync_utils.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["time"] }
