name: CI Yul equivalent EVM

on:
  pull_request:
  merge_group:
  push:
    branches:
      - staging
      - trying
      - main
      - evm-equivalence-yul

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: "recursive"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7

      - name: Install yarn
        run: corepack enable
        # https://yarnpkg.com/corepack

      - name: Install preprocessor
        run: npm install -g preprocess-cli-tool

      - name: Install solc
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum \
            && sudo apt-get update \
            && sudo apt-get install -y solc=0.8.24

      - name: Download zksolc
        run: |
          curl -L -o bin/zksolc https://github.com/matter-labs/zksolc-bin/releases/download/v1.4.0/zksolc-linux-amd64-musl-v1.4.0 \
            && chmod +x bin/zksolc

      - name: Build system contracts
        run: |
          cd contracts/system-contracts \
            && yarn install \
            && yarn build

      - name: Build EVM test contracts
        run: |
          cd etc/evm-contracts-test-data \
            && yarn install \
            && yarn build

      - name: Build zkEVM test contracts
        run: |
          cd etc/contracts-test-data \
            && sed -i 's/zksolc-macosx-arm64/zksolc-linux-amd64-musl/' hardhat.config.ts \
            && yarn install \
            && yarn build

      - name: Compile EVM interpreter
        run: ZKSYNC_HOME=$(pwd) PATH=$(pwd)/bin:$PATH bash recompile_interpreter.sh

      - name: Export needed env vars
        run: |
          export ZKSYNC_HOME=$(pwd) \
            && export PATH=$ZKSYNC_HOME/bin:$PATH

      - name: Run unit tests
        run: ZKSYNC_HOME=$(pwd) cargo test evm_simulator
        env:
          RUSTFLAGS: ""